header = "pthread.h"

ints = ["PTHREAD_BARRIER_SERIAL_THREAD",
        "PTHREAD_CANCEL_ASYNCHRONOUS",
        "PTHREAD_CANCEL_ENABLE",
        "PTHREAD_CANCEL_DEFERRED",
        "PTHREAD_CANCEL_DISABLE",
        "PTHREAD_CREATE_DETACHED",
        "PTHREAD_CREATE_JOINABLE",
        "PTHREAD_EXPLICIT_SCHED",
        "PTHREAD_INHERIT_SCHED",
        "PTHREAD_MUTEX_DEFAULT",
        "PTHREAD_MUTEX_ERRORCHECK",
        "PTHREAD_MUTEX_NORMAL",
        "PTHREAD_MUTEX_RECURSIVE",
        "PTHREAD_MUTEX_ROBUST",
        "PTHREAD_MUTEX_STALLED",
        "PTHREAD_ONCE_INIT",
        "PTHREAD_PRIO_INHERIT",
        "PTHREAD_PRIO_NONE",
        "PTHREAD_PRIO_PROTECT",
        "PTHREAD_PROCESS_SHARED",
        "PTHREAD_PROCESS_PRIVATE",
        "PTHREAD_SCOPE_PROCESS",
        "PTHREAD_SCOPE_SYSTEM",
        ]
